### ISSUE TITLE
Issue with columns in datapackage table

### ISSUE THREAD

**Issue by romainsacchi** [polca/ScenarioLink#23]
@marc-vdm I have added an extra column "Scope" to indicate the geographical scope of the available scenarios.
This is however messing up with the current columns.
<img width="787" alt="Screenshot 2023-10-07 at 15 48 17" src="https://github.com/polca/ScenarioLink/assets/22473067/96d0ba61-6ff3-4bfd-8046-a99a4e66bbf0">

**Comment by marc-vdm** [comment]
Fixed, but keep in mind that this now breaks for everyone that doesn't update to the version with the fix

**Comment by marc-vdm** [comment]
I can write the df such that it will only show columns we choose (by default we show everything), but this will only ever work for new releases as I didn't think of this before.

**Comment by romainsacchi** [comment]
Right, but this is inde velopment, so users will have to update every now and then.
Also, not entirely fixed:
````
Fetching data from Zenodo: https://zenodo.org/api/records/ecoinvent 3.9 cutoff
````
The URL is not properly made (should be the zenodo record ID).

**Comment by romainsacchi** [comment]
Awesome, thanks.
